name: OCI Image Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  oci_publish:
    name: Build and publish the OCI image
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Build the Docker image
        run: docker build . -f Dockerfile-build --tag cli:${{ github.ref_name }}