name: OCI Image Publish
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # We only want to run on version tags
jobs:
  oci_publish:
    name: Build and publish the OCI image
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # pin@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # pin@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8c0edbc76e98fa90f69d9a2c020dcb50019dc325 # pin@v2

      - name: Login to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # pin@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # pin@v3
        with:
          context: .
          file: Dockerfile-release
          platforms: linux/amd64,linux/arm64
          push: true
          tags: linode/cli:${{ github.ref_name }},linode/cli:latest
