name: Publish Wiki

on:
  push:
    branches: [main]

concurrency:
  group: publish-wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Generate App Installation Token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # pin@v1
        with:
          app_id: ${{ secrets.CLI_RELEASE_APP_ID }}
          private_key: ${{ secrets.CLI_RELEASE_PRIVATE_KEY }}
          repository: lgarber-akamai/linode-cli

      - uses: Andrew-Chen-Wang/github-wiki-action@v4
