name: Remote Release Trigger
on:
  repository_dispatch:
    types: [cli-release]
jobs:
  remote-release-trigger:
    runs-on: ubuntu-latest
    environment: CLI Automated Release
    steps:
      - name: Generate App Installation Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.CLI_RELEASE_APP_ID }}
          private_key: ${{ secrets.CLI_RELEASE_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the next minor version
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semvers.outputs.v_minor }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          body: Built from Linode OpenAPI spec ${{ github.event.client_payload.spec_version }}
          tag_name: ${{ steps.semvers.outputs.v_minor }}